### ISSUE TITLE
Not working for 2.12

### ISSUE THREAD

**Issue by asynchronizd** [nelstein/nravepay#11]
I've tried so many things. After debugging for hours I found that there's a problem with trippledes package. It is unable to generate the base64 key and throwing 

```dart
List<int> is not subtype of Null error.
```

Please help me solve the issue.

```dart
 var initializer = PayInitializer(
        amount: 450,
        email: 'email@email.com',
        txRef: 'TXREF-${DateTime.now().microsecondsSinceEpoch}',
        narration: 'New payment',
        country: 'NG',
        currency: 'NGN',
        firstname: 'Nelson',
        lastname: 'Eze',
        phoneNumber: '09092343432',
        onComplete: (result) {
          if (result.status == HttpStatus.success) {
            if (result.card != null) {
              print(result.card);
              //  saveCard(card);
            }
          }
          print(result.message);
        });
    return PayManager().prompt(context: context, initializer: initializer);
  }
```

This is the code I'm using, V3 though.

**Comment by asynchronizd** [comment]
solved the problem by replacing tripledes with `dart_3ds`

But now I'm getting this error

```shell
I/flutter (17637): Response Text:
I/flutter (17637): {"status":"success","message":"Charge authorization data required","meta":{"authorization":{"mode":"pin","fields":["pin"]}}}
I/flutter (17637):
I/flutter (17637): type 'Null' is not a subtype of type 'int'
I/flutter (17637): HttpStatus.error
I/flutter (17637): Result Message:  Error occurred.
```

It never asked for PIN

**Comment by nelsonweze** [comment]
Hi @holy-dev , I will look into this. Could you check if it gives same error on V2?

**Comment by asynchronizd** [comment]
@nelstein  For v2

```shell
I/flutter (28479): Response Text:
I/flutter (28479): {"status":"success","message":"AUTH_SUGGESTION","data":{"suggested_auth":"PIN"}}
I/flutter (28479):
I/flutter (28479): type 'Null' is not a subtype of type 'int'
```

Also I would suggest you to shift from tripledes package as soon other people will also have the same problem.

**Comment by nelsonweze** [comment]
Yeah, it seemed like the original tripledes package was not being supported so we forked it and made changes. hence the [tripledes_nullsafety](https://pub.dev/packages/tripledes_nullsafety). One more question, are you using the latest version , nravepay: ^1.0.5+1?

**Comment by asynchronizd** [comment]
@nelstein yes, I am.

**Comment by asynchronizd** [comment]
@nelstein anything on the issue?

**Comment by asynchronizd** [comment]
@nelstein I've downgraded dart sdk to 2.7.0 it's working just fine, even with the tripledes package. But PIN auth payment is failing.

**Comment by nelsonweze** [comment]
I just tested the example code with the following details and it worked.

Flutter beta version: 2.5.0-5.2.pre

```dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_svg: ^0.22.0
  tripledes_nullsafety: ^1.0.1
  intl: ^0.17.0
  get_it: ^6.0.0
  webview_flutter: ^2.0.2
  async: ^2.6.1
```

Could you clone that and let me know if it works? Also were you working on test or live environment?

**Comment by nelsonweze** [comment]
Closing this issue as no response in a while. Feel free to re-open if it still persists
