### ISSUE TITLE
Payment fails  with tripledes runtime error

### ISSUE THREAD

**Issue by asapJ** [nelstein/nravepay#19]
From looking at the error's stack trace, I noticed this was coming from the tripledes package used with the plugin, since you authored both packages and I only added  directly referenced this, I figured I should open the issue here.

The exact error:  'Null' is not a subtype of type int in type cast.
Current flutter version: 2.5.2

Steps to reproduce:
1. Setup plugin
2. Setup Initializer and call Paymanger().prompt()
3. Fill in card details and hit pay.

PS: Run with sound nullsafety

**Comment by nelsonweze** [comment]
Sorry, If I hadn't missed your PS, this would have been fixed a lot sooner
Checkout nravepay: ^1.2.2 if you are still experiencing this issue. 

Closing this also. Feel free to reopen if anything
