### ISSUE TITLE
Split Payment Functionality

### ISSUE THREAD

**Issue by rohitsangwan01** [nelstein/nravepay#20]
Hey , great package , just one doubt , so i want that users pay directly to vendor from my flutter app , and i got commison out of it , so by using this split functionality , can i achieve this , and will payment settledown to bank accounts of vendors and mine , instantly ??

**Comment by nelsonweze** [comment]
Hi @rohitsangwan01  yes that's right. [Flutterwave split](https://developer.flutterwave.com/docs/split-payment) works that way.

**Comment by rohitsangwan01** [comment]
Great , thanks for confirmation
