### ISSUE TITLE
Adding another country brings Bad state: No Element

### ISSUE THREAD

**Issue by kelvinnmugendi** [nelstein/nravepay#6]
Tried passing KE and currency as KES and it brings an error Bad state: No Element

**Comment by nelsonweze** [comment]
@kevinrobert3  could you attach a code example so I can understand  better what you did?

**Comment by kelvinnmugendi** [comment]
I did not add anything special just passed KE as the country and KES as the currency   

`Future<void> _startPayment(BuildContext context) async {
    var initializer = PayInitializer(
        amount: 50,
        email: 'email@email.com',
        txRef: 'TXREF-${DateTime.now().microsecondsSinceEpoch}',
        narration: 'New payment',
        country: 'KE',
        currency: 'KES',
        firstname: 'Nelson',
        lastname: 'Eze',
        phoneNumber: '09092343432',
        onComplete: (result) {
          if (result.status == HttpStatus.success) {
            if (result.card != null) {
              log.log(result.card.toMap().toString());
              //  saveCard(card);
              log.log(result.card.token);
            }
          }
          print(result.message);
        });
    return PayManager().prompt(context: context, initializer: initializer);
  }`

**Comment by nelsonweze** [comment]
I get it now. I only included a specific list of currencies when I was testing, forgot to remove it. Fixing it now. Will tell you when I make a push.

**Comment by nelsonweze** [comment]
Try one more time with nravepay: ^1.0.5. Should be fine now

**Comment by kelvinnmugendi** [comment]
That worked
