### ISSUE TITLE
Recurring charges not possible in test mode 

### ISSUE THREAD

**Issue by kelvinnmugendi** [nelstein/nravepay#8]
I am suddenly getting this error when using live keys and staging is set to false. I am not on the test environment. I am not repeating a charge

**Comment by nelsonweze** [comment]
Did you switch to live mode on your Dashboard? if yes, can I get a minimal reproducible code?

**Comment by kelvinnmugendi** [comment]
This is the initialization in main 
 `NRavePayRepository.setup(
      publicKey: "FLWPUBK-0c9050-X",
      encryptionKey: "f037f177a",
      secKey: "FLWSECK-f0301f-X",
      // publicKey: "FLWPUBK_TEST-0fe4685f3a-X",
      // encryptionKey: "FLWSECK_TEST66819be1",
      // secKey: "FLWSECK_TEST-a05f0487858-X",
      staging: false,
      version: Version.v2);`
I have redacted the keys no worries. And this is the code to start payment 
`  Future<void> _startPayment(BuildContext context) async {
    var initializer = PayInitializer(
        amount: 50,
        email: 'ro@gmail.com',
        txRef: 'TXREF-${DateTime.now().microsecondsSinceEpoch}',
        narration: 'New payment',
        country: 'KE',
        currency: 'KES',
        firstname: 'K',
        lastname: 'Bundi',
        phoneNumber: '25479098684',
        onComplete: (result) {
          if (result.status == HttpStatus.success) {
            if (result.card != null) {
              log.log(result.card.toMap().toString());
              //  saveCard(card);
              log.log(result.card.token);
            }
          }
          log.log(result.message.toString());
        });
    return PayManager().prompt(context: context, initializer: initializer);
  }`

In test mode, this works and I get that card token, however when i switch it to live mode as in the code above, which is using live keys, I get the Recurring charges not possible in test mode. That is the log from the log in the code, `log(result.message)` there is also an error before that log printed to console `charge Http status error [400]`. 
I changed nothing, just changed the plugin version to 1.0.5. I even had to run `flutter clean` to make sure file remnants from previous packages were not messing up my code

**Comment by nelsonweze** [comment]
Okay checking.. You also didn't use the test card for the live environment, right?

**Comment by kelvinnmugendi** [comment]
No I am using a live card on the live environment

**Comment by kelvinnmugendi** [comment]
Did you manage to reproduce the issue

**Comment by nelsonweze** [comment]
No not really, I would really like if someone else reported same issue so I can confirm it's general

**Comment by kelvinnmugendi** [comment]
Okay unless someone has a different issue that is different from this one, this is the solution for this issue. So, apparently, when using live credentials, on the Flutterwave dashboard, it should also be live. The error for me comes when the app is using live credentials and on the dashboard, it's set to test mode.  If this is the case, the error comes up. So, live credentials with live mode on dashboard solves this
