### ISSUE TITLE
"Add Credit Card" text is misleading.

### ISSUE THREAD

**Issue by asapJ** [nelstein/nravepay#9]
I was reading through the docs and found [this image](https://raw.githubusercontent.com/nelstein/nravepay/main/screenshots/card_list.png) .

Debit cards are primarily/largely used in NG and that "add Credit Card" text is misleading. It might look ignorable, but from a UX POV it could use some tuning.  Something generic like "add card", "new card" would suffice even for countries with large credit card support.

Good job on the plugin btw.

**Comment by asapJ** [comment]
Also for flexibility, the plugin could be tweaked as follows:
1. If there are no saved cards proceed straight to card payment screen.
2. Add a flag to enable/disable save card feature from plugin initialization. Some apps might not implement that and users might expect the feature to work since they see it.

**Comment by nelsonweze** [comment]
@asapJ Thanks for the suggestions. I will work on them by weekend.

**Comment by nelsonweze** [comment]
Try again with version 1.0.5+1

**Comment by asapJ** [comment]
@nelstein good job with the changes, I will close the issue now.
Remember to update the docs and also package screenshots  too.
